dist: focal
language: node_js
node_js:
  - '14.21.1'
  - '16.18.0'
  - '18.12.0'

os:
  - linux

cache:
  directories:
    - ./node_modules

services:
  - docker

install:
  - npm ci --no-progress

script:
  - npm run lint
  - npm run prettier:check
  - npm run test
  - cp .env.dist .env
  - docker-compose up -d --build postgres
  - docker ps -a
  - npm run test:e2e
  - npm run build
